version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      FLASK_ENV: development

  frontend:
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
